### ISSUE TITLE
EPR Data Enterer map to PractitionerRole instead of Practitione (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#93] opened 2021-03-06 07:07 UTC
ch.fhir.ig.ch-core#1.2.0 /StructureDefinition-ch-ext-epr-dataenterer.html

Data Enterer is currently mapped to Practitioner. However this does not allow to provide the organization information with it. Suggest to change the link to PractitionerRole that the Practitioner and Organization can be provided.

In CDA dateEnterer is mapped to hl7:assignedEntity, which can contain 0..1 assignedPerson and 0..1 representedOrganization.

Oliver Egger, ahdis

**Comment by oliveregger** [comment] 2021-03-06 08:28
duplicate of #91

**Closed** 2021-03-22 08:36 UTC
Labels: STU 1.2.0 Ballot
